### ISSUE TITLE
Can not update table entry with python code

### ISSUE THREAD

**Issue by croessner** [pief/python-netsnmpagent#33] opened 2017-05-11 16:23 UTC
Hi,

I set up a table with python. Now I want to change values at runtime from inside the python script. Therefor I tried to store references of the types of a row:

If I try...:

```
rcnt = agent.Counter32(500)
rflag = agent.Integer32(99)

row = self._stats_table.addRow([agent.Integer32(1)])
row.setRowCell(2, agent.DisplayString("Some name"))
row.setRowCell(3, rcnt)
row.setRowCell(4, rflag)

...

rcnt.update(1000)
rflag.update(5000)
```

...the table is not updated and I do not understand why. I always have to clear() the whole table and set values newly. Is that the only way doing it? Unfortunately the simple-example only demonstrates updates on scalar types.

**Comment by abhiksarkar** [comment] 2017-05-19 15:01
I tried exactly the same approach for the same reason... and it didn't work for me either.
 
However, I was able to get it to work by maintaining references to the row and cell and calling
`row.setRowCell()` again with the same object. I didn't have to clear the whole table and set it up again.

I am not very experienced with Python in general, and and the ctypes module in particular, but I was very curious about why this doesn't work as expected. Having analyzed this a bit, it seems like it might be because:
- the objects are passed by value, not reference (probably wrong interpretation on my part)
- or, more likely, because the netsnmp makes a copy of the data when the corresponding function is called. From the netsnmp API documentation for the function `netsnmp_set_row_column`, 

> Sets a given column in a row with data given a type, value, and length. Data is memdup'ed by the function, at least if type != SNMP_NOSUCHINSTANCE and if value_len > 0.

**Comment by pief** [comment] 2017-08-09 08:09
Please always also indicate what distribution and especially which version of net-snmp libraries you're using as they can behave differently.

**Comment by pouralijan** [comment] 2018-06-17 15:21
You see this error?

 ```
Error in packet.
 Reason: notWritable (That object does not support modification)
```

**Comment by pief** [comment] 2018-10-29 22:40
Duplicate of #27, @pouralijan has posted a fix there.

**Closed by pief** 2018-10-29 22:40 UTC
